spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${IAM_DB_HOST:localhost}:${IAM_DB_PORT:3306}/${IAM_DB_BASE:active_auth_iam_core}?characterSet=utf-8&useUnicode=true&characterEncoding=utf8
    hikari:
      username: ${IAM_DB_USER:root}
      password: ${IAM_DB_PASS:root}

privateKey: |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvHXi2hTRxR+x4
  jn7KgNu7PEGovZksz6QNt5sLiVY4FZzlNtfjYI5kommBILjgc+iWwMixlhKIQDBq
  88nWKwYjDdwDLiVAlr+cSBHuvq8R5PP/wuV1WZ/WCfzHnsGcmWAc2QUHIS2eGV+0
  lUQ7eTEkXycRZ/H7eh6Md7AHD/N/1UWPSu3jjGUC8wZkDf2wDmGdP74Bg8dz1F3L
  T9m43ObhHN08mZxd96lE3UcNUrFKs6jTOMq4dXbSeiOa7n9SU5kYtTkOIElMvzRd
  Zqpu3TMQWvrJKUWr/VdPkqwiO7dLrvLFF8c29/QucHc5Oso//HgIbq8DP8kBPVze
  Zp+V3KppAgMBAAECggEAEupFCroSsxXIxjDmIyuOEIhuszJfpEZ9evnVJobcKEy1
  WND2utnIJ7ifWtJVBfGfMwF57CzArbT5ReQ1bgvRquGpXTKT1YkzA0eJoFc6g91O
  Odcsf+OBb1Y+1rUgRrEOf681atK7obMt8kyZRS9PDpW0m521tqs3N4cKHYksjScn
  j++DINiAqwJS4O0oP3q/ai3KMV/98e40kYJYJReUHUKa5IshTXGY9hvqDa00bnHa
  WKCRejNHEMh+DnyPrscHUyX0LiRtaRemYnGZZG/f9GwRUKNeDUjf4BhLuuoollRF
  pkoCgcaOcjDe3C9Ex7Qa7N7rE9QNXBGg59SBbsHIzQKBgQDXbR/x5qsv9Ezwkej8
  NNLLE9jgLLpKCiiRz5wN+vmnawc4FUiJPi4vE8vVuhP+0LJyJfctLE5xvOaR7GTx
  nP8PL1WSwkMFF7DUOJfQtNrToCtVnJ3Mf4wIVtyPgGtsxesAGJkO/9JPuKjgLZcZ
  P4hcRwE1lLHrXfGUdfRC7c4hRwKBgQDQGLoCA56TbMg6OnAu1+IftO9emk3oiAGz
  6KW9qI+0BXtwdVHyvL1Gj6PA5jQGbJ0xhjP6YxRsHH/m62C4FFd22N+C2lNkVm7F
  CTdLyMpXeLhHmBHeC65rLhUL/UZPWcvCjmthLZj+zh153BR8a9zZy2oTrW/8828w
  CRG5XqMuzwKBgQDBL5ANKzFrAKcauY541ZoPGU5Mwm+QxAlbsRUeCGpns3g22AdD
  ZCqgdx09HfCee2L7MIa30NrL7n3KcHaZoZOtd2JDCMh3QaaGufWS6Qyv6RvTW267
  G8plFBgY7C3pzpcOcACaTdm5OjzfRKMStkG/lsFD3oOrMYTaAOk6N+25MwKBgFoW
  mlBM6NXB/lzW98IPy+EWH5rBCoFkf/g2+6nD05KH3Qyufa+sbfSiMq5L+rHdS6Ap
  DU+UnT7Ah86cj96hT8wvz3OCuR9zG7lJaBry7kY4CO9VskaCoBvec1Yha9LmeQPd
  TDdh2h5VdQVQdb33pEDVgzLJnvXPHY+aHYY2pkaZAoGAOEgy166Kw0Tf/WQx71Xd
  EBNM51gF050AU4eWOnYnHBINZCl/R4R1Npk7yvBvTMiLAiYc0x0asl8yT/1RitAp
  uYq6nReCXwkpKmvijJGXgDRkuEzOjsqiXo0Au4XPTuZ36U9LAVtwuNer5fh1/K9I
  i6E6onqU+FFqMHBLV4qQ1xc=
  -----END PRIVATE KEY-----
